export const MAX_FILE_SIZE_MB = 25;

export const CONVERSION_TOOLS = [
  {
    id: "pdf-to-word",
    title: "PDF to Word",
    description: "Convert PDF documents to editable .docx",
    icon: "document-text",
    endpoint: "/convert/pdf-to-word",
    fieldName: "file",
    multiple: false,
    accept: ["application/pdf"],
    outputExt: "docx",
    requiresPages: false,
  },
  {
    id: "pdf-to-excel",
    title: "PDF to Excel",
    description: "Extract PDF content into .xlsx spreadsheet",
    icon: "grid",
    endpoint: "/convert/pdf-to-excel",
    fieldName: "file",
    multiple: false,
    accept: ["application/pdf"],
    outputExt: "xlsx",
    requiresPages: false,
  },
  {
    id: "word-to-pdf",
    title: "Word to PDF",
    description: "Convert .doc/.docx files to PDF",
    icon: "reader",
    endpoint: "/convert/word-to-pdf",
    fieldName: "file",
    multiple: false,
    accept: [
      "application/msword",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ],
    outputExt: "pdf",
    requiresPages: false,
  },
  {
    id: "excel-to-pdf",
    title: "Excel to PDF",
    description: "Convert .xls/.xlsx files to PDF",
    icon: "stats-chart",
    endpoint: "/convert/excel-to-pdf",
    fieldName: "file",
    multiple: false,
    accept: [
      "application/vnd.ms-excel",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ],
    outputExt: "pdf",
    requiresPages: false,
  },
  {
    id: "image-to-pdf",
    title: "Images to PDF",
    description: "Combine JPG/PNG images into one PDF",
    icon: "images",
    endpoint: "/convert/image-to-pdf",
    fieldName: "files",
    multiple: true,
    accept: ["image/jpeg", "image/png"],
    outputExt: "pdf",
    requiresPages: false,
  },
  {
    id: "pdf-merge",
    title: "Merge PDFs",
    description: "Combine multiple PDF files into one",
    icon: "layers",
    endpoint: "/pdf/merge",
    fieldName: "files",
    multiple: true,
    accept: ["application/pdf"],
    outputExt: "pdf",
    requiresPages: false,
  },
  {
    id: "pdf-split",
    title: "Split PDF",
    description: "Extract selected pages from a PDF",
    icon: "cut",
    endpoint: "/pdf/split",
    fieldName: "file",
    multiple: false,
    accept: ["application/pdf"],
    outputExt: "pdf",
    requiresPages: true,
  },
  {
    id: "ocr",
    title: "OCR Extract",
    description: "Extract text from scans and images",
    icon: "text",
    endpoint: "/ocr/extract",
    fieldName: "file",
    multiple: false,
    accept: ["application/pdf", "image/jpeg", "image/png"],
    outputExt: "txt",
    requiresPages: false,
    isOcr: true,
  },
  {
    id: "pdf-compress",
    title: "Compress PDF",
    description: "Reduce PDF file size",
    icon: "archive",
    endpoint: "/pdf/compress",
    fieldName: "file",
    multiple: false,
    accept: ["application/pdf"],
    outputExt: "pdf",
    requiresPages: false,
  },
];

export function getToolById(id) {
  return CONVERSION_TOOLS.find((tool) => tool.id === id);
}
