-- =====================================================================
-- FreePDFScanner -- production schema BASELINE (snapshot)
--
-- Source:   live Supabase project zdegimgixjpirtivrrgc ("DocuScanner-web",
--           Postgres 17), read from the system catalogs on 2026-10-05.
-- Purpose:  the repository only holds 8 of the ~38 migrations that were
--           applied to production (many via the dashboard / MCP, several of
--           them QA or debugging steps). This file records the schema as it
--           actually is, so a new project can be rebuilt and so changes can
--           be reviewed against a known starting point.
--
-- THIS IS A SNAPSHOT, NOT A MIGRATION. Do NOT run it against production
-- (everything here already exists). To build a fresh project: apply this file
-- once to an empty database, then apply only migrations dated AFTER
-- 2026-10-05. Table data, grants and Auth settings are not included.
--
-- Not captured here (set up by Supabase or by hand):
--   * Auth configuration (email confirmation ON, Site URL, redirect allow-list)
--   * Edge Function secrets (SUPABASE_SECRET_KEY etc.)
--   * Grants on public functions (ad_assets_caller_is_admin is executable by
--     `authenticated` only; revoked from public)
--   * product_settings seed rows
-- =====================================================================

-- ==== TABLES ====
create table if not exists public.ad_campaigns (
  id uuid not null default gen_random_uuid(),
  name text not null,
  advertiser_name text not null,
  status text not null default 'draft'::text,
  starts_at timestamp with time zone not null,
  ends_at timestamp with time zone not null,
  target_countries text[] not null default '{}'::text[],
  target_devices text[] not null default '{}'::text[],
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  priority integer not null default 5,
  frequency_cap_per_session integer,
  target_regions text[] not null default '{}'::text[],
  target_paths text[] not null default '{}'::text[],
  timezone text not null default 'UTC'::text,
  days_of_week smallint[],
  start_time time without time zone,
  end_time time without time zone
);

create table if not exists public.ad_creatives (
  id uuid not null default gen_random_uuid(),
  campaign_id uuid not null,
  slot_code text not null,
  asset_url text not null,
  click_url text,
  alt_text text,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  title text,
  description text,
  cta_text text,
  device_variant text not null default 'all'::text,
  width integer,
  height integer,
  destination_type text not null default 'link'::text,
  embed_url text,
  media_type text not null default 'image'::text,
  storage_path text,
  mime_type text,
  file_size_bytes bigint
);

create table if not exists public.ad_events (
  id bigint generated by default as identity,
  campaign_id uuid not null,
  creative_id uuid not null,
  event_type text not null,
  slot_code text not null,
  user_id uuid,
  session_id text,
  device_type text,
  country_code text,
  created_at timestamp with time zone not null default now(),
  path text,
  region text,
  city text,
  postal_code text,
  location_source text,
  county_district_lga text,
  neighborhood_suburb text
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity,
  admin_user_id uuid,
  action text not null,
  target_type text,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.admin_users (
  user_id uuid not null,
  role text not null default 'admin'::text,
  display_name text,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity,
  event_name text not null,
  visitor_id text,
  session_id text,
  user_id uuid,
  path text,
  referrer text,
  ip_hash text,
  country_code text,
  region text,
  city text,
  device_type text,
  browser text,
  operating_system text,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  postal_code text,
  location_source text,
  county_district_lga text,
  neighborhood_suburb text
);

create table if not exists public.analytics_export_jobs (
  id uuid not null default gen_random_uuid(),
  requested_by uuid not null,
  format text not null,
  delivery_method text not null,
  email_to text,
  date_from timestamp with time zone not null,
  date_to timestamp with time zone not null,
  filters jsonb not null default '{}'::jsonb,
  status text not null default 'queued'::text,
  storage_path text,
  result_count bigint,
  error_message text,
  requested_at timestamp with time zone not null default now(),
  completed_at timestamp with time zone
);

create table if not exists public.deleted_account_cooldowns (
  email_hash text not null,
  deleted_at timestamp with time zone not null default now()
);

create table if not exists public.documents (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  title text not null default 'Untitled document'::text,
  storage_path text not null,
  mime_type text not null default 'application/pdf'::text,
  file_size bigint not null,
  page_count integer,
  is_password_protected boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.features (
  code text not null,
  name text not null,
  description text,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.live_sessions (
  session_id text not null,
  visitor_id text not null,
  user_id uuid,
  path text,
  tool text,
  activity text,
  device_type text,
  browser text,
  operating_system text,
  country_code text,
  region text,
  started_at timestamp with time zone not null default now(),
  last_seen timestamp with time zone not null default now(),
  city text,
  postal_code text,
  location_source text,
  county_district_lga text,
  neighborhood_suburb text
);

create table if not exists public.plan_features (
  plan_code text not null,
  feature_code text not null,
  enabled boolean not null default true,
  limit_value bigint,
  limit_unit text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.product_settings (
  key text not null,
  value jsonb not null,
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.subscription_plans (
  code text not null,
  name text not null,
  description text,
  is_active boolean not null default true,
  monthly_price numeric(12,2) not null default 0,
  annual_price numeric(12,2) not null default 0,
  currency text not null default 'USD'::text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.usage_counters (
  user_id uuid not null,
  period_start date not null,
  scans_count bigint not null default 0,
  ocr_pages bigint not null default 0,
  conversions_count bigint not null default 0,
  storage_bytes bigint not null default 0,
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.user_profiles (
  user_id uuid not null,
  display_name text,
  country_code text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.user_subscriptions (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  plan_code text not null,
  status text not null default 'active'::text,
  provider text,
  provider_subscription_id text,
  starts_at timestamp with time zone not null default now(),
  ends_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- ==== PRIMARY KEYS ====
alter table public.ad_campaigns add constraint ad_campaigns_pkey primary key (id);
alter table public.ad_creatives add constraint ad_creatives_pkey primary key (id);
alter table public.ad_events add constraint ad_events_pkey primary key (id);
alter table public.admin_audit_logs add constraint admin_audit_logs_pkey primary key (id);
alter table public.admin_users add constraint admin_users_pkey primary key (user_id);
alter table public.analytics_events add constraint analytics_events_pkey primary key (id);
alter table public.analytics_export_jobs add constraint analytics_export_jobs_pkey primary key (id);
alter table public.deleted_account_cooldowns add constraint deleted_account_cooldowns_pkey primary key (email_hash);
alter table public.documents add constraint documents_pkey primary key (id);
alter table public.features add constraint features_pkey primary key (code);
alter table public.live_sessions add constraint live_sessions_pkey primary key (session_id);
alter table public.plan_features add constraint plan_features_pkey primary key (plan_code, feature_code);
alter table public.product_settings add constraint product_settings_pkey primary key (key);
alter table public.subscription_plans add constraint subscription_plans_pkey primary key (code);
alter table public.usage_counters add constraint usage_counters_pkey primary key (user_id, period_start);
alter table public.user_profiles add constraint user_profiles_pkey primary key (user_id);
alter table public.user_subscriptions add constraint user_subscriptions_pkey primary key (id);

-- ==== CHECK CONSTRAINTS ====
alter table public.ad_campaigns add constraint ad_campaigns_dates check (ends_at > starts_at);
alter table public.ad_campaigns add constraint ad_campaigns_days_of_week_check check (days_of_week is null or days_of_week <@ array[0::smallint, 1::smallint, 2::smallint, 3::smallint, 4::smallint, 5::smallint, 6::smallint]);
alter table public.ad_campaigns add constraint ad_campaigns_frequency_cap_per_session_check check (frequency_cap_per_session is null or frequency_cap_per_session > 0);
alter table public.ad_campaigns add constraint ad_campaigns_status check (status = any (array['draft'::text, 'scheduled'::text, 'active'::text, 'paused'::text, 'completed'::text, 'archived'::text]));
alter table public.ad_creatives add constraint ad_creatives_destination_type_check check (destination_type = any (array['link'::text, 'embed'::text]));
alter table public.ad_creatives add constraint ad_creatives_device_variant_check check (device_variant = any (array['all'::text, 'desktop'::text, 'mobile'::text]));
alter table public.ad_creatives add constraint ad_creatives_media_type_check check (media_type = any (array['image'::text, 'video'::text]));
alter table public.ad_events add constraint ad_events_event_type check (event_type = any (array['impression'::text, 'click'::text]));
alter table public.admin_users add constraint admin_users_role check (role = any (array['super_admin'::text, 'admin'::text, 'analyst'::text]));
alter table public.analytics_events add constraint analytics_events_name check (event_name = any (array['page_view'::text, 'app_open'::text, 'signup_started'::text, 'signup_completed'::text, 'login'::text, 'logout'::text, 'scan_started'::text, 'scan_completed'::text, 'document_uploaded'::text, 'document_created'::text, 'conversion_started'::text, 'conversion_completed'::text, 'document_downloaded'::text, 'feature_used'::text, 'error'::text]));
alter table public.analytics_export_jobs add constraint analytics_export_jobs_dates check (date_to > date_from);
alter table public.analytics_export_jobs add constraint analytics_export_jobs_delivery check (delivery_method = any (array['download'::text, 'email'::text]));
alter table public.analytics_export_jobs add constraint analytics_export_jobs_email_required check (delivery_method <> 'email'::text or email_to is not null);
alter table public.analytics_export_jobs add constraint analytics_export_jobs_format check (format = any (array['csv'::text, 'pdf'::text]));
alter table public.analytics_export_jobs add constraint analytics_export_jobs_status check (status = any (array['queued'::text, 'processing'::text, 'completed'::text, 'failed'::text]));
alter table public.plan_features add constraint plan_features_limit_nonnegative check (limit_value is null or limit_value >= 0);
alter table public.subscription_plans add constraint subscription_plans_code_format check (code ~ '^[a-z0-9_]+$'::text);
alter table public.usage_counters add constraint usage_counters_nonnegative check (scans_count >= 0 and ocr_pages >= 0 and conversions_count >= 0 and storage_bytes >= 0);
alter table public.user_subscriptions add constraint user_subscriptions_status check (status = any (array['trialing'::text, 'active'::text, 'past_due'::text, 'cancelled'::text, 'expired'::text, 'paused'::text]));

-- ==== FOREIGN KEYS ====
alter table public.ad_creatives add constraint ad_creatives_campaign_id_fkey foreign key (campaign_id) references public.ad_campaigns(id) on delete cascade;
alter table public.ad_events add constraint ad_events_campaign_id_fkey foreign key (campaign_id) references public.ad_campaigns(id) on delete cascade;
alter table public.ad_events add constraint ad_events_creative_id_fkey foreign key (creative_id) references public.ad_creatives(id) on delete cascade;
alter table public.ad_events add constraint ad_events_user_id_fkey foreign key (user_id) references auth.users(id) on delete set null;
alter table public.admin_audit_logs add constraint admin_audit_logs_admin_user_id_fkey foreign key (admin_user_id) references auth.users(id) on delete set null;
alter table public.admin_users add constraint admin_users_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade;
alter table public.analytics_events add constraint analytics_events_user_id_fkey foreign key (user_id) references auth.users(id) on delete set null;
alter table public.analytics_export_jobs add constraint analytics_export_jobs_requested_by_fkey foreign key (requested_by) references auth.users(id) on delete cascade;
alter table public.documents add constraint documents_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade;
alter table public.live_sessions add constraint live_sessions_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade;
alter table public.plan_features add constraint plan_features_feature_code_fkey foreign key (feature_code) references public.features(code) on delete cascade;
alter table public.plan_features add constraint plan_features_plan_code_fkey foreign key (plan_code) references public.subscription_plans(code) on delete cascade;
alter table public.usage_counters add constraint usage_counters_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade;
alter table public.user_profiles add constraint user_profiles_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade;
alter table public.user_subscriptions add constraint user_subscriptions_plan_code_fkey foreign key (plan_code) references public.subscription_plans(code);
alter table public.user_subscriptions add constraint user_subscriptions_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade;

-- ==== INDEXES ====
create index deleted_account_cooldowns_deleted_at_idx on public.deleted_account_cooldowns using btree (deleted_at);
create index ad_events_created_idx on public.ad_events using btree (created_at desc);
create index plan_features_feature_idx on public.plan_features using btree (feature_code);
create index analytics_events_country_created_idx on public.analytics_events using btree (country_code, created_at desc);
create index analytics_events_visitor_created_idx on public.analytics_events using btree (visitor_id, created_at desc);
create index user_subscriptions_plan_idx on public.user_subscriptions using btree (plan_code);
create unique index user_subscriptions_active_user_idx on public.user_subscriptions using btree (user_id) where (status = any (array['trialing'::text, 'active'::text, 'past_due'::text, 'paused'::text]));
create index analytics_export_jobs_status_idx on public.analytics_export_jobs using btree (status, requested_at);
create index ad_events_geo_created_at_idx on public.ad_events using btree (country_code, region, city, created_at);
create index analytics_events_visitor_created_at_idx on public.analytics_events using btree (visitor_id, created_at);
create index live_sessions_last_seen_idx on public.live_sessions using btree (last_seen desc);
create index analytics_events_country_created_at_idx on public.analytics_events using btree (country_code, created_at);
create index documents_user_id_idx on public.documents using btree (user_id);
create index user_subscriptions_user_idx on public.user_subscriptions using btree (user_id);
create index ad_creatives_campaign_idx on public.ad_creatives using btree (campaign_id);
create index analytics_events_created_idx on public.analytics_events using btree (created_at desc);
create index admin_audit_logs_admin_created_idx on public.admin_audit_logs using btree (admin_user_id, created_at desc);
create index admin_audit_logs_created_idx on public.admin_audit_logs using btree (created_at desc);
create index live_sessions_user_id_idx on public.live_sessions using btree (user_id);
create index analytics_events_event_created_idx on public.analytics_events using btree (event_name, created_at desc);
create index ad_events_campaign_created_idx on public.ad_events using btree (campaign_id, created_at desc);
create index ad_events_country_created_at_idx on public.ad_events using btree (country_code, created_at);
create index analytics_events_geo_created_at_idx on public.analytics_events using btree (country_code, region, city, created_at);
create index analytics_events_user_created_idx on public.analytics_events using btree (user_id, created_at desc);
create index ad_events_creative_idx on public.ad_events using btree (creative_id);
create index analytics_export_jobs_requested_idx on public.analytics_export_jobs using btree (requested_by, requested_at desc);
create index ad_events_user_idx on public.ad_events using btree (user_id);

-- ==== ROW LEVEL SECURITY (enabled on every public table) ====
alter table public.ad_events enable row level security;
alter table public.analytics_export_jobs enable row level security;
alter table public.documents enable row level security;
alter table public.ad_creatives enable row level security;
alter table public.deleted_account_cooldowns enable row level security;  -- no policies: service role only
alter table public.live_sessions enable row level security;
alter table public.subscription_plans enable row level security;
alter table public.features enable row level security;
alter table public.plan_features enable row level security;
alter table public.user_profiles enable row level security;
alter table public.user_subscriptions enable row level security;
alter table public.usage_counters enable row level security;
alter table public.product_settings enable row level security;
alter table public.ad_campaigns enable row level security;
alter table public.analytics_events enable row level security;
alter table public.admin_users enable row level security;
alter table public.admin_audit_logs enable row level security;

-- ==== POLICIES ====
-- User-owned data
create policy "Users can view their own documents" on public.documents as permissive for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "Users can insert their own documents" on public.documents as permissive for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy "Users can update their own documents" on public.documents as permissive for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can delete their own documents" on public.documents as permissive for delete to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can view their own profile" on public.user_profiles as permissive for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "Users can insert their own profile" on public.user_profiles as permissive for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy "Users can update their own profile" on public.user_profiles as permissive for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy "Users can view their own subscriptions" on public.user_subscriptions as permissive for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "Users can view their own usage" on public.usage_counters as permissive for select to authenticated
  using ((select auth.uid()) = user_id);

-- Public catalogue (plans and features)
create policy "Public can read active subscription plans" on public.subscription_plans as permissive for select to anon, authenticated
  using (is_active = true);
create policy "Public can read features" on public.features as permissive for select to anon, authenticated
  using (true);
create policy "Public can read plan features" on public.plan_features as permissive for select to anon, authenticated
  using (exists (select 1 from public.subscription_plans p where p.code = plan_features.plan_code and p.is_active = true));

-- Deny-all: reached only through Edge Functions / server code with the secret key
create policy "No direct public access to product settings" on public.product_settings as permissive for all to anon, authenticated using (false) with check (false);
create policy "No direct public access to ad campaigns" on public.ad_campaigns as permissive for all to anon, authenticated using (false) with check (false);
create policy "No direct public access to ad creatives" on public.ad_creatives as permissive for all to anon, authenticated using (false) with check (false);
create policy "No direct public access to ad events" on public.ad_events as permissive for all to anon, authenticated using (false) with check (false);
create policy "No direct public access to analytics events" on public.analytics_events as permissive for all to anon, authenticated using (false) with check (false);
create policy "No direct public access to admin users" on public.admin_users as permissive for all to anon, authenticated using (false) with check (false);
create policy "No direct public access to admin audit logs" on public.admin_audit_logs as permissive for all to anon, authenticated using (false) with check (false);
create policy "No direct public access to analytics export jobs" on public.analytics_export_jobs as permissive for all to anon, authenticated using (false) with check (false);
create policy "No direct public access to live sessions" on public.live_sessions as permissive for all to anon, authenticated using (false) with check (false);

-- Storage: private "documents" bucket, objects keyed "<user-id>/<document-id>/document.pdf"
create policy "Users can view their own document objects" on storage.objects as permissive for select to authenticated
  using (bucket_id = 'documents'::text and (storage.foldername(name))[1] = (select (auth.uid())::text));
create policy "Users can upload their own document objects" on storage.objects as permissive for insert to authenticated
  with check (bucket_id = 'documents'::text and (storage.foldername(name))[1] = (select (auth.uid())::text));
create policy "Users can update their own document objects" on storage.objects as permissive for update to authenticated
  using (bucket_id = 'documents'::text and (storage.foldername(name))[1] = (select (auth.uid())::text))
  with check (bucket_id = 'documents'::text and (storage.foldername(name))[1] = (select (auth.uid())::text));
create policy "Users can delete their own document objects" on storage.objects as permissive for delete to authenticated
  using (bucket_id = 'documents'::text and (storage.foldername(name))[1] = (select (auth.uid())::text));

-- Storage: public "ad-assets" bucket; reads are public, writes need an active admin / super_admin
create policy "Anyone can list ad assets" on storage.objects as permissive for select to public
  using (bucket_id = 'ad-assets'::text);
create policy "Admins can upload ad assets" on storage.objects as permissive for insert to authenticated
  with check (bucket_id = 'ad-assets'::text and public.ad_assets_caller_is_admin());
create policy "Admins can replace ad assets" on storage.objects as permissive for update to authenticated
  using (bucket_id = 'ad-assets'::text and public.ad_assets_caller_is_admin())
  with check (bucket_id = 'ad-assets'::text and public.ad_assets_caller_is_admin());
create policy "Admins can delete ad assets" on storage.objects as permissive for delete to authenticated
  using (bucket_id = 'ad-assets'::text and public.ad_assets_caller_is_admin());

-- ==== FUNCTIONS ====
create or replace function public.returning_visitor_ids(visitor_ids text[], before timestamp with time zone)
 returns table(visitor_id text)
 language sql
 stable
 set search_path to 'public'
as $function$
  select distinct e.visitor_id
  from public.analytics_events e
  where e.visitor_id = any(visitor_ids)
    and e.created_at < before
$function$;

create or replace function public.ad_assets_caller_is_admin()
 returns boolean
 language plpgsql
 stable security definer
 set search_path to 'public'
as $function$
begin
  return exists (
    select 1 from public.admin_users au
    where au.user_id = auth.uid() and au.is_active and au.role in ('super_admin', 'admin')
  );
end;
$function$;
-- revoke all on function public.ad_assets_caller_is_admin() from public;
-- grant execute on function public.ad_assets_caller_is_admin() to authenticated;

create or replace function public.email_cooldown_hash(address text)
 returns text
 language sql
 immutable
 set search_path to 'public'
as $function$
  select encode(sha256(convert_to(lower(btrim(address)), 'UTF8')), 'hex')
$function$;

create or replace function public.signup_email_in_cooldown(check_email text)
 returns boolean
 language sql
 stable security definer
 set search_path to 'public'
as $function$
  select exists (
    select 1
    from public.deleted_account_cooldowns c
    where c.email_hash = public.email_cooldown_hash(check_email)
      and c.deleted_at > now() - interval '24 hours'
  )
$function$;

create or replace function public.block_signup_during_cooldown()
 returns trigger
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
begin
  if new.email is not null and public.signup_email_in_cooldown(new.email) then
    raise exception 'account_recently_deleted'
      using errcode = 'P0001',
            hint = 'This address belongs to an account deleted less than 24 hours ago.';
  end if;
  return new;
end
$function$;

create or replace function public.admin_analytics_event_groups(p_from timestamp with time zone, p_to timestamp with time zone)
 returns jsonb
 language sql
 stable
 set search_path to 'public'
as $function$
  with win as (
    select * from public.analytics_events where created_at >= p_from and created_at < p_to
  ),
  returning_v as (
    select v.visitor_id
    from (select distinct visitor_id from win where visitor_id is not null) v
    where exists (
      select 1 from public.analytics_events p where p.visitor_id = v.visitor_id and p.created_at < p_from
    )
  ),
  grouped as (
    select (created_at at time zone 'utc')::date as d,
           event_name, visitor_id, session_id, user_id,
           country_code, region, city, county_district_lga, neighborhood_suburb, location_source,
           device_type, browser, operating_system, referrer,
           count(*) as n
    from win
    group by 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'created_at', g.d::text,
    'event_name', g.event_name,
    'visitor_id', g.visitor_id,
    'session_id', g.session_id,
    'user_id', g.user_id,
    'country_code', g.country_code,
    'region', g.region,
    'city', g.city,
    'county_district_lga', g.county_district_lga,
    'neighborhood_suburb', g.neighborhood_suburb,
    'location_source', g.location_source,
    'device_type', g.device_type,
    'browser', g.browser,
    'operating_system', g.operating_system,
    'referrer', g.referrer,
    'n', g.n,
    'returning', r.visitor_id is not null
  )), '[]'::jsonb)
  from grouped g
  left join returning_v r on r.visitor_id = g.visitor_id
$function$;

create or replace function public.admin_analytics_ad_groups(p_from timestamp with time zone, p_to timestamp with time zone)
 returns jsonb
 language sql
 stable
 set search_path to 'public'
as $function$
  select coalesce(jsonb_agg(jsonb_build_object(
    'created_at', g.d::text,
    'event_type', g.event_type,
    'country_code', g.country_code,
    'region', g.region,
    'city', g.city,
    'county_district_lga', g.county_district_lga,
    'neighborhood_suburb', g.neighborhood_suburb,
    'device_type', g.device_type,
    'n', g.n
  )), '[]'::jsonb)
  from (
    select (created_at at time zone 'utc')::date as d, event_type, country_code, region, city,
           county_district_lga, neighborhood_suburb, device_type, count(*) as n
    from public.ad_events
    where created_at >= p_from and created_at < p_to
    group by 1, 2, 3, 4, 5, 6, 7, 8
  ) g
$function$;

create or replace function public.admin_export_events_page(p_from timestamp with time zone, p_to timestamp with time zone, p_after bigint, p_limit integer, p_event_names text[] default null::text[], p_country text default null::text, p_region text default null::text, p_city text default null::text, p_district text default null::text, p_neighborhood text default null::text, p_device text default null::text)
 returns jsonb
 language plpgsql
 stable
 set search_path to 'public'
as $function$
declare
  where_extra text := '';
  result jsonb;
begin
  if p_event_names is not null then where_extra := where_extra || format(' and e.event_name = any(%L::text[])', p_event_names); end if;
  if p_country is not null then where_extra := where_extra || format(' and e.country_code = %L', p_country); end if;
  if p_region is not null then where_extra := where_extra || format(' and e.region = %L', p_region); end if;
  if p_city is not null then where_extra := where_extra || format(' and e.city = %L', p_city); end if;
  if p_district is not null then where_extra := where_extra || format(' and e.county_district_lga = %L', p_district); end if;
  if p_neighborhood is not null then where_extra := where_extra || format(' and e.neighborhood_suburb = %L', p_neighborhood); end if;
  if p_device is not null then where_extra := where_extra || format(' and e.device_type = %L', p_device); end if;

  execute format($q$
    with page as materialized (
      select e.id, e.event_name, e.visitor_id, e.session_id, e.user_id, e.path, e.referrer,
             e.country_code, e.region, e.city, e.county_district_lga, e.neighborhood_suburb,
             e.postal_code, e.location_source, e.device_type, e.browser, e.operating_system,
             e.properties, e.created_at
      from public.analytics_events e
      where e.created_at >= $1 and e.created_at < $2 and e.id > $3 %s
      order by e.id
      limit least(greatest($4, 1), 5000)
    ),
    returning_v as materialized (
      select v.visitor_id
      from (select distinct visitor_id from page where visitor_id is not null) v
      where exists (select 1 from public.analytics_events p where p.visitor_id = v.visitor_id and p.created_at < $1)
    )
    select jsonb_build_object(
      'scanned', (select count(*) from page),
      'last_id', (select max(id) from page),
      'rows', coalesce((
        select jsonb_agg(to_jsonb(pg) || jsonb_build_object('is_returning', r.visitor_id is not null) order by pg.id)
        from page pg left join returning_v r on r.visitor_id = pg.visitor_id
      ), '[]'::jsonb)
    )
  $q$, where_extra)
  into result
  using p_from, p_to, p_after, p_limit;
  return result;
end
$function$;

-- ==== TRIGGERS ====
create trigger block_signup_during_cooldown before insert on auth.users
  for each row execute function public.block_signup_during_cooldown();

-- ==== STORAGE BUCKETS ====
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('documents', 'documents', false, null, null)
on conflict (id) do nothing;
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('ad-assets', 'ad-assets', true, 62914560, null)  -- 60 MB
on conflict (id) do nothing;

-- ==== SEED / SETTINGS (values as of 2026-10-05; not data to re-insert blindly) ====
-- product_settings: admin_dashboard_enabled=true, ads_enabled=true, analytics_enabled=true,
--   analytics_ip_storage="hash_only", analytics_raw_event_retention_days=90,
--   launch_mode="free_plus_ads", premium_enabled=false, premium_activation_window_months=6
-- subscription_plans: 2 rows; features: 20 rows; plan_features: 34 rows.
